### ISSUE TITLE
Prepare a Cocoapods integration

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-mobile-sdk#1]
We need to have a Cocoapods integration in order to simplify library integration in iOS apps.

In Cocoapods integration, IMO we should follow the steps that Flurry and Crittercism do in their SDK:

- build a framework
- create a pod that downloads and installs the framework

**Comment by hvge** [comment]
You can use `pod 'PowerAuth2'` for PowerAuth integration now.
