### ISSUE TITLE
Add high-level methods to iOS encryptor

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-mobile-sdk#11]
On server and on Android, we currently have high-level methods to process E2EE - instead of byte[], we are able to pass Object / Class and serialize the data ourselves. We could provide similar support on iOS as well.

**Comment by hvge** [comment]
After discussing internally, we closing this issue. The reason is that on iOS platform, there's no easy way for object to JSON serialization (especially in swift)
