### ISSUE TITLE
Implement NSUserDefaults group sharing

### ISSUE THREAD

**Issue by bobro2** [lime-company/lime-security-powerauth-mobile-sdk#12]
Prepare setter for App Group identifier. Or similar functionality that can let you choose what NSUserDefaults to use. For example iOS Widgets don't have access to **[NSUserDefaults standardUserDefaults]** only to **[[NSUserDefaults alloc] initWithSuiteName:@"group.com.company.app"]**

**Comment by petrdvorak** [comment]
We currently have only one place where we use `NSUserDefaults`:

https://github.com/lime-company/lime-security-powerauth-mobile-sdk/blob/4cf5cc2514d197e9c720abb53123700476609580/proj-xcode/Classes/sdk/PowerAuthSDK.m#L86

```objc
// Make sure to reset keychain data after app re-install.
// Important: This deletes all Keychain data in all PowerAuthSDK instances!
if ([[NSUserDefaults standardUserDefaults] boolForKey:PA2Keychain_Initialized] == NO) {
    [_statusKeychain deleteAllData];
    [_sharedKeychain deleteAllData];
    [_biometryOnlyKeychain deleteAllData];
    [[NSUserDefaults standardUserDefaults] setBool:YES forKey:PA2Keychain_Initialized];
    [[NSUserDefaults standardUserDefaults] synchronize];
}
```

The code is used to determine if the application was re-installed and in case it was (value is not present in `NSUserDefaults`), `PA2Keychain` instances are cleared and flag is stored in `NSUserDefaults`.

We can proceed here in multiple ways - we can allow customization of `NSUserDefaults` instance using `PA2KeychainConfiguration` instance, or we can make the code not compile for widget / extension code.

@bobro2 Can you please elaborate what is the required use case here on your end? Also, how do you share iOS Keychain - using the default group ID?

**Comment by petrdvorak** [comment]
OK, after understanding the issue better, I suggest following improvement on SDK:

- `PA2KeychainConfiguration` will have new attribute to allow group ID configuration.
- In case this attribute is `nil`, we will use `standardUserDefaults`, otherwise we will use custom user defaults with provided `suiteName`.
- Developer who started using SDK with `standardUserDefaults` will be responsible for manual migration of data to a new user defaults.
