### ISSUE TITLE
State cannot be stored after computing 1FA when EEK is used

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-mobile-sdk#14]
Steps to reproduce:

1. Have an activation that was created with EEK.
2. Create an instance of this activation and do NOT set EEK.
3. Compute 1FA signature using the activation.
4. Signature is correctly computed.
=> State cannot be saved, therefore counter is not incremented.

**Comment by hvge** [comment]
I need to know which factor is used in this scenario. For me, It looks more like a bad error handling than the missing serialization, or bad counter computation.

**Comment by petrdvorak** [comment]
Obviously, `possession` factor is used.

**Comment by petrdvorak** [comment]
@ludek.vlk We are unable to reproduce this - can you please elaborate little more about what happens and what specifically fails inside the SDK? Is it iOS / Android specific?

**Comment by petrdvorak** [comment]
We have verified this issue in the specific implementation and the issue really was that there were multiple instances of `PowerAuthSDK` class working with the same activation state. When using one instance as recommended, everything worked correctly.
