### ISSUE TITLE
Allow disabling PALog macro even in case DEBUG is on

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-mobile-sdk#20]
After mobile developers finish debugging PowerAuth integration, our SDK logs are no longer useful to them and clutter the debugging log. Currently, we automatically disable the `PALog` macro in case `DEBUG` is not set.

We should also add an extra macro to manually disable the logging, even in the case of `DEBUG`.

**Comment by hvge** [comment]
Now it's possible to define `DISABLE_PA2_LOG` or `ENABLE_PA2_LOG` to force disable or enable the log.
