### ISSUE TITLE
Intermittent issue PA2ErrorDomain Code: 4 on custom activation (iOS)

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-mobile-sdk#44]
Some instances of the custom activation on iOS fail with the `PA2ErrorDomain Code: 4`. We are currently not able to reproduce the issue and it happens to a very small fraction of the user base, but we should investigate it anyway.

**Comment by petrdvorak** [comment]
Our code has several rooms for improvement:

- We should be checking the output of JSON parsing for errors in custom activation method, so that we can differentiate JSON parsing related errors better.
- We should be checking for HTTP status code - while the server should technically return only status codes handled by SDK, we are unable to assure this in case of the custom activation, since the back-end code is implemented by the bank API provider (not part of our SDK).

**Comment by hvge** [comment]
This is a kind of improvement. When there's an error during the activation, the application has usually only one option how to react on that situation and must restart the activation process. So, the actual goal is _make our SDK more friendly for debugging_. 

I agree that we need to improve our error reporting. Here's my additional list of ideas:

- It's unfortunate that SDK is hiding some error states reported from low level code or reinterprets them to more vague meaning. We should just extend "core" error codes with values needed in high level code.
- We should add textual description to reported NSErrors. That might improve debugging a lot.

**Comment by hvge** [comment]
Just for note. I've created a separate tickets (#49 #50) for that error reporting improvements.

**Comment by hvge** [comment]
Not a bug. An error reported back to customer's application is correct, but not very descriptive. We'll address this reporting enhancements in separate issues.
