### ISSUE TITLE
IAddBiometryFactorListener not called when fingerprint dialog dismissed by system "back" button

### ISSUE THREAD

**Issue by petrfuka** [lime-company/lime-security-powerauth-mobile-sdk#57]
When adding fingerprint authentication to an existing activation using PowerAuthSDK.addBiometryFactor(), the fingerprint dialog is displayed. If it is dismissed with the "Cancel" button, the supplied IAddBiometryFactorListener gets called on its onAddBiometryFactorFailed() method. If the dialog is dismissed with the back button, the listener is not called at all.

The same happens with PowerAuthSDK.commitActivation() and the ICommitActivationWithFingerprintListener's onFingerprintDialogCancelled() method.

The same happens when the dialog is dismissed by clicking outside of its area.

Roughly connected: The IAddBiometryFactorListener should probably also have some onDialogCancelled method to differentiate between "Wrong PIN" (fingerprint not recognized?) and "dialog dismissed".

**Comment by petrdvorak** [comment]
This issue is caused by the recent change in SDK - we allowed the fingerprint dialog to be cancelled using the device button, but we do not handle this change with callback anywhere.
